name: Production CD

on:
    push:
        branches:
            - master

jobs:
    production:
        name: Deploy a new version of Motorga's react client
        runs-on: ubuntu-latest

        steps:
            - name: Use a secure shell to deploy a new version of Motorga for the master branch
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                port: ${{ secrets.SSH_PORT }}
                key: ${{ secrets.SSH_KEY }}
                script: |
                  cd /home/debian/react &&
                  git checkout . &&
                  git checkout master &&
                  git pull &&
                  npm install &&
                  npm run build

            - name: Send mail
              if: ${{ failure() }}
              uses: dawidd6/action-send-mail@v2
              with:
                # mail server settings
                server_address: ssl0.ovh.net
                server_port: 465
                # user credentials
                username: ${{ secrets.EMAIL_USERNAME }}
                password: ${{ secrets.EMAIL_PASSWORD }}
                # email subject
                subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
                # email body as text
                body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
                # comma-separated string, send email to
                to: quentinhermiteau@gmail.com
                # from email name
                from: Github Actions